name: Python Codestyle

# CINTENT >> MANUAL_TRIGGER
# on:
#   workflow_dispatch:
#   push:
#     branches: [ master ]
#     paths:
#       - 'binding/python/*.py'
#       - 'demo/python/*.py'
#   pull_request:
#     branches: [ master, 'v[0-9]+.[0-9]+' ]
#     paths:
#       - 'binding/python/*.py'
#       - 'demo/python/*.py'
on: [repository_dispatch, workflow_dispatch]

jobs:
  check-python-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

    - name: Install dependencies
      run: pip install flake8 pep8-naming

    - name: Check python codestyle
      run: flake8 --ignore=F401,F403,F405 --max-line-length=120 binding/python demo/python
      
    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}